[package]
name = "artemis_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["rt-multi-thread", "sync", "macros"] }
rdkafka = { version = "0.36", features = ["cmake-build"] }
serde_json = "1.0"
serde = "1.0"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
notify = "6.1"
csv = "1.3"
env_logger = "0.11"
mongodb = "3"
sqlx = { version = "0.8", features = [
  "postgres",
  "runtime-tokio-native-tls",
  "macros",
] }
polars = { version = "0.41.3", features = [
  "lazy",
  "rows",
  "strings",
  "regex",
  "concat_str",
] }
sea-query = "0.31"
sea-query-binder = { version = "0.6.0", features = ["sqlx-postgres"] }
regex = "1.10"
lazy_static = "1.5"
unidecode = "0.3"

[dev-dependencies]
clap = "4.5"
dotenv = "0.15"                                                # or the latest version
criterion = { version = "0.5.1", features = ["html_reports"] }


[[example]]
name = "csv_to_kafka"
path = "examples/csv_to_kafka.rs"

[[example]]
name = "simple_kafka_consumer"
path = "examples/simple_kafka_consumer.rs"

[[example]]
name = "kafka_to_mongo"
path = "examples/kafka_to_mongo.rs"

[[example]]
name = "csv_jdd_to_postgres"
path = "examples/csv_jdd_to_postgres.rs"

[[example]]
name = "transform_jdd_normalisation"
path = "examples/transform_jdd_normalisation.rs"

[[bench]]
name = "transform_benchmark"
harness = false
