services:
  mongo:
    image: mongo:7.0.11-jammy
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USR
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PWD
    volumes:
      - mongo-data:/data/db
    networks:
      - localnet
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USR
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PWD
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USR}:${MONGO_ROOT_PWD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - localnet

  #running kafka without zookeeper (using KRaft)
  #Kafka Service
  kafka:
    image: "bitnami/kafka:3.4"
    container_name: kafka-node
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:9094,CONTROLLER://:9093, PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:29092,EXTERNAL://localhost:9094,PLAINTEXT://kafka:9092
      #Identify all other controllers in the cluster
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    volumes:
      - kafka-data:/bitnami
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - localnet

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8084:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka
    networks:
      - localnet

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PWD
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Persist data in a volume
    networks:
      - localnet

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGUI_DEFAULT_EMAIL # Change to your email
      PGADMIN_DEFAULT_PASSWORD: $PGUI_DEFAULT_PWD # Change to your password
    ports:
      - "5050:80" # Access pgAdmin web interface at http://localhost:5050
    depends_on:
      - postgres # Ensure pgAdmin starts after PostgreSQL
    networks:
      - localnet

volumes:
  mongo-data:
  kafka-data:
    driver: local

networks:
  localnet:
    attachable: true
