---- Base app schema


-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    username VARCHAR(128) NOT NULL UNIQUE,
    typ USER_TYP NOT NULL DEFAULT 'User',

    -- Auth
    pwd VARCHAR(256),
    pwd_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    token_salt UUID NOT NULL DEFAULT gen_random_uuid(),

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Agent

CREATE TABLE agent (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    -- FKs
    owner_id BIGINT NOT NULL,

    -- Properties
    name VARCHAR(256) NOT NULL,
    -- For now only support 'dev' provider
    ai_provider VARCHAR(256) NOT NULL DEFAULT 'dev',
    -- For now only support 'parrot' model
    ai_model VARCHAR(256) NOT NULL DEFAULT 'parrot',

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Conv
CREATE TYPE conv_kind AS ENUM ('OwnerOnly', 'MultiUsers');

CREATE TYPE conv_state AS ENUM ('Active', 'Archived');

CREATE TABLE conv (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    -- FKs
    owner_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,

    -- Properties
    title VARCHAR(256),
    kind CONV_KIND NOT NULL DEFAULT 'OwnerOnly',
    state CONV_STATE NOT NULL DEFAULT 'Active',

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE conv ADD CONSTRAINT fk_conv_agent
FOREIGN KEY (agent_id) REFERENCES agent (id)
ON DELETE CASCADE;


-- Conv Participants
CREATE TABLE conv_user (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    -- Properties / FKs
    conv_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    -- Machine User Properties
    auto_respond BOOLEAN NOT NULL DEFAULT false,

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Conv Messages
CREATE TABLE conv_msg (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    -- FKs
    conv_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL, -- should be came as cid

    -- Properties
    content VARCHAR(1024) NOT NULL,

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE conv_msg ADD CONSTRAINT fk_conv_msg_conv
FOREIGN KEY (conv_id) REFERENCES conv (id)
ON DELETE CASCADE;

ALTER TABLE conv_user ADD CONSTRAINT fk_conv_user_conv
FOREIGN KEY (user_id) REFERENCES "user" (id)
ON DELETE CASCADE;
