[env]
SERVICE_PWD_KEY="CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
SERVICE_TOKEN_KEY="9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw"
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minutes
POSTGRES_PWD="postgres"
POSTGRES_DB_NAME="artemis"
POSTGRES_USER="postgres"
PGUI_DEFAULT_PWD="postgres"
PGUI_DEFAULT_EMAIL="nguyencaokha131995@gmail.com"
MONGO_ROOT_USR="root"
MONGO_ROOT_PWD="example"
